---

- src: ome.postgresql
  version: 4.0.0

- name: ome.ice
  src: "https://github.com/ome/ansible-role-ice/archive/\
    efe4e218fe25d39c6e0bdb89570b7cf2d3f799a8.tar.gz"
  version: 4.1.0

- src: ome.omero_server
  version: 3.0.0

- src: ome.omero_web
  version: 3.0.1

- src: ome.omero_user
  version: 0.1.2
